### ISSUE TITLE
Refactor code that associates filenames with protein codes

### ISSUE THREAD

**Issue by mathuin** [osuosl/pgd#51]
Right now we have at least three different pieces of code in the splicer app that associate protein codes like `1XYZ` with files like `./pdb/pdb1xyz.ent.gz`.  We do it in the FTP update script, in the protein import script, and the tests.

Each of these are implemented differently.  They all need to change once we start using the rsync archive which has files in locations like `/data/pdb/xy/pdb1xyz.ent.gz`.  I think we should write one routine, put it somewhere in the splicer app where everything can see it, and then make all the others use that one.

Where to put it?  This "app" started life as a collection of not-really-Django code.  Right now I'm leaning towards creating another file (say tools.py) for this routine and any others like it that we come across.  Then it's a simple matter of `from pgd_splicer.tools import pdbfile` or the like.

Thoughts?  I can mock something up as a demo if that will help.

**Comment by pop** [comment]
@mathuin I agree that a `tools.py` or a `lib.py` file would be helpful. In the future once I get around to actually de-crufting the codebase that'll be where a lot of duplicated code will probably go.

As far as naming I don't care if it's `tools` or `lib` or `misc` as long as it's well documented where it is and what it's purpose is.

**Comment by mathuin** [comment]
Okay #52 has been submitted to implement this fix.

**Comment by mathuin** [comment]
This issue was resolved by #52.
