### ISSUE TITLE
Integration Test Script is too fragile

### ISSUE THREAD

**Issue by pop** [osuosl/pgd#56]
The integration test does cool things like `./integration-test.sh: line 26: [[: >>>: syntax error: operand expected (error token is ">>>")` and `./integration-test.sh: line 57: [[: >>>: syntax error: operand expected (error token is ">>>")` and beautifully crafted statements like:

```
$DOCKER bash -c 'echo "from pgd_core.models import Protein; Protein.objects.all().delete(); exit()" | python manage.py shell' >/dev/null
```

and

```
BEFORE=`$DOCKER bash -c 'echo "from pgd_core.models import Protein; print Protein.objects.count(); exit()" | python manage.py shell' | tail -1 | awk '{ print $2 }' | tr -d '[[:space:]]'`
```

to remedy this I suggest adding some python management commands that accomplish the same tasks with a little less... bash.

**Comment by mathuin** [comment]
Okay, there's a new branch `add-management-commands` which currently implements `coredb`, a new management command.  Right now the command only has one option: `--count`, which counts the proteins, chains, and residues in the database.  Once `--clear` is added, the integration test script will be cleaned up to match.  The same command will eventually support `--dump` and `--import` for transferring databases to files and back, which will be helpful in database upgrades.

**Comment by mathuin** [comment]
Turns out dump and import aren't needed as this can already be done with dumpdata and loaddata, so I'm calling this one good!
